name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: |
          sudo npm install

      - name: Build frontend
        run: |
          cd client
          sudo npm install
          sudo npm run build

      - name: Deploy to Server
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ${{ secrets.SERVER_USER }}
          IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_KEY" > private_key
          chmod 600 private_key
          sudo cp -r client/build/* /var/www/html
          #sudo cp -r /* /var/www/backend(do tis step mannually)
          ssh -i private_key -o StrictHostKeyChecking=no $USER@$IP 'sudo npm i pm2 -g && cd /var/www/backend && sudo pm2 start app.js' # assuming pm2 is used for process management
